-- STUDENT TABLE

CREATE TABLE STUDENT(
    roll_num NUMBER PRIMARY KEY,
    name VARCHAR2(30) NOT NULL,
    address VARCHAR2(40) NOT NULL
);

--ALTER TABLE STUDENT MODIFY roll_num NUMBER CONSTRAINT pk_rollnum PRIMARY KEY;

DESC STUDENT;

-- INSERT INTO SYNTAX
-- INSERT INTO TABLE_NAME VALUES (1,)
INSERT INTO STUDENT VALUES(1,'SONU','PUNE');
INSERT INTO STUDENT(roll_num,name,address) VALUES(2,'SAHIL','ABAD');
INSERT INTO STUDENT(roll_num,name,address) VALUES(10,'SCOTT','NY CITY');


INSERT INTO STUDENT VALUES(&roll_num,'&name','&address');

-- DIPLICATE ROLL NUMBER
INSERT INTO STUDENT VALUES(1,'MONU','MUMBAI');

-- NAME WILL BE BLANK
INSERT INTO STUDENT VALUES(5,'MUMBAI');

SELECT * FROM STUDENT;

CREATE TABLE COURSE 
(
    c_id NUMBER,
    c_name VARCHAR2(30),
    roll_num NUMBER REFERENCES STUDENT(ROLL_NUM)
);



INSERT INTO COURSE VALUES (10,'PYTHON',1);
INSERT INTO COURSE VALUES (20,'JAVA',1);
INSERT INTO COURSE VALUES (20,'JAVA',2);
INSERT INTO COURSE VALUES (10,'PYTHON',2);
INSERT INTO COURSE VALUES (30,'MANCHIN LEARNING',3);
INSERT INTO COURSE VALUES (10,'PYTHON',3);

SELECT * FROM COURSE;

SELECT * FROM STUDENT;

SELECT s.roll_num, s.name, c.c_Id, c.c_name FROM STUDENT s, COURSE c WHERE s.roll_num = c.roll_num AND s.name ='SONU';


-- HOW TO DELETE THE ROWS
-- DELETE ALL RECORD FOR SONU WITH PYTHON COURSE
DELETE FROM COURSE WHERE roll_num = 1 AND c_name = 'JAVA';

-- BELOW QUERY WILL FIALED AS THERE ARE CHILD RECORDS AND WE HAVENT CREATED TABLE USINING CASCADE CLAUSE
DELETE FROM STUDENT WHERE roll_num = 2;

-- 
DELETE FROM STUDENT WHERE roll_num = 1;


-- UPDATE
UPDATE COURSE SET C_ID = 50 WHERE c_name = 'PYTHON';
SELECT * FROM COURSE;

--SYNTAX
--UPDATE TABLE_NAME
--SET COLUMNS = VALUES
--WHERE CONDTION

SELECT * FROM HR.EMPLOYEES;

SELECT SALARY FROM HR.EMPLOYEES ORDER BY 1 DESC;

ALTER TABLE COURSES RENAME TO COURSE;

-- WHO ARE THE PYTHON SUBSCRIBER

SELECT s.name,c.c_id,c.c_name FROM STUDENT s, COURSE c WHERE s.roll_num = c.roll_num AND c.c_name='PYTHON';



