SELECT * FROM EMPLOYEES;

SELECT * FROM EMPLOYEES WHERE ROWNUM < 2;

-- TWO HIGHEST SALARIES
SELECT SALARY FROM EMPLOYEES WHERE ROWNUM < 3 ORDER BY 1 DESC;

-- DUPLICATE FIRST_NAME OR NO OF TYPE FIRST NAME OCCURED
SELECT FIRST_NAME, COUNT(FIRST_NAME) AS OCCURENCE FROM EMPLOYEES GROUP BY FIRST_NAME 
HAVING COUNT(FIRST_NAME) > 1 ORDER BY 2 DESC;

-- max salary
SELECT MAX(SALARY) FROM EMPLOYEES;

-- MIN SALARY
SELECT MIN(SALARY) FROM EMPLOYEES;

-- AVERAGE SALARY
SELECT ROUND(AVG(SALARY),2) AS AVG_SALARY FROM EMPLOYEES;

SELECT * FROM SH.CUSTOMERS ORDER BY CUST_ID;
DESC SH.CUSTOMERS;

-- CUSTOMERS BY GENDERS
SELECT CUST_GENDER, COUNT(CUST_GENDER) AS C_COUNT FROM SH.CUSTOMERS GROUP BY CUST_GENDER;

-- SALES TABLE
SELECT * FROM SH.SALES;

-- TOTAL NUMBER OF SPECIFIC PRODUCT ORDER
SELECT PROD_ID, COUNT(PROD_ID) AS NO_OF_PURCHASE FROM SH.SALES GROUP BY PROD_ID ORDER BY 1;

-- TOTAL CUSTOMERS
SELECT DISTINCT(COUNT(CUST_ID)) FROM SH.SALES;

SELECT TIME_ID FROM SH.SALES WHERE ROWNUM < 2 ORDER BY 1 DESC;

-- SORT CUSTOMER BY BIRTHYEAR
SELECT * FROM SH.CUSTOMERS ORDER BY CUST_YEAR_OF_BIRTH;

-- TOTAL NUMBER OF CUSTOMER
SELECT COUNT(CUST_ID) FROM SH.CUSTOMERS;
-- 55500 CUSTMERS

SELECT CUST_POSTAL_CODE, COUNT(CUST_POSTAL_CODE) AS TNO_CUST_LIVES_ON_PIN FROM SH.CUSTOMERS GROUP BY CUST_POSTAL_CODE ORDER BY 2;

-- HOW MANY USERS HAVE BOUTH PRODUCT NO 13
SELECT COUNT(DISTINCT(CUST_ID)) AS PROD_13 FROM SH.SALES WHERE PROD_ID = 13;

-- TOTAL SALES BY PRODUCT
SELECT PROD_ID, SUM(QUANTITY_SOLD * AMOUNT_SOLD) AS TOTAL_SALES FROM SH.SALES GROUP BY PROD_ID ORDER BY 2;

SELECT DISTINCT(S.PROD_ID), P.PROD_NAME FROM SH.SALES S, SH.PRODUCTS P 
WHERE S.PROD_ID = P.PROD_ID 
ORDER BY 1;

SELECT * FROM SH.PRODUCTS;

-- Write a SQL query to find the products which have continuous increase in sales every year?
SELECT  PROD_ID, SUBSTR(TIME_ID,7) AS YYYY, SUM(QUANTITY_SOLD * AMOUNT_SOLD) AS TOTAL_SALES 
FROM SH.SALES
WHERE PROD_ID IN (13,14,15)
GROUP BY PROD_ID, SUBSTR(TIME_ID,7)
ORDER BY 1 ASC;



