-- Join Tutorials
DESC DEPARTMENTS;
DESC LOCATIONS;

-- SCENARIO 1: NATURAL JOIN (FETCH CITY FOR ALL DEPARTMENTS)

-- THE BEST PART OF USING NATURAL JOIN IS THAT WE DONT' NEED TO SPECIFY JOIN COLUMNS
SELECT department_name, city FROM DEPARTMENTS NATURAL JOIN LOCATIONS; 

-- SCENARIO 2: When source and target table has more than 1 comman column

DESC EMPLOYEES;
DESC DEPARTMENTS;

-- MANAGER_ID AND DEPARTMENT_ID ARE COMMON COLOUMN IN TABLE 
SELECT first_name, department_name, manager_id FROM EMPLOYEES NATURAL JOIN DEPARTMENTS;

-- ABOVE QUERIES ALSO CALLED AS PURE NATURAL JOIN

-- NATURAL JOIN USING ON CLAUSE (THIS QUERY WILL PRODUCE SAME RESULT)
SELECT FIRST_NAME, DEPARTMENT_NAME FROM EMPLOYEES E JOIN DEPARTMENTS D
ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID AND E.MANAGER_ID = D.MANAGER_ID);


-- SCENARIO 3: NATURAL JOIN BY DEFAULT MATCHES ALL COLUMNS WHAT IF WE WANT TO CHECK ONLY ONE COLUMN?
-- IN SUCH CASES WE CAN USE `USING CLAUSE`
SELECT FIRST_NAME, DEPARTMENT_NAME FROM EMPLOYEES JOIN DEPARTMENTS USING (manager_id);
SELECT FIRST_NAME, DEPARTMENT_NAME FROM EMPLOYEES JOIN DEPARTMENTS USING (DEPARTMENT_ID);


-- RIGHT OUTER JOIN ---
