SELECT COUNT(DISTINCT(EMPLOYEE_ID)) FROM HR.employees;

SELECT COUNT(EMPLOYEE_ID) FROM HR.employees;

CREATE TABLE emp( FirstName VARCHAR2(100), LastName VARCHAR2(100), Country VARCHAR2(100))

-- Duplicate records
INSERT INTO emp(FirstName,LastName,Country )values ('Raj','Gupta','India');
INSERT INTO emp(FirstName,LastName,Country )values ('Raj','Gupta','India');
INSERT INTO emp(FirstName,LastName,Country )values ('Mohan','Kumar','USA');
INSERT INTO emp(FirstName,LastName,Country )values ('James','Barry','UK');
INSERT INTO emp(FirstName,LastName,Country )values ('James','Barry','UK');
INSERT INTO emp(FirstName,LastName,Country )values ('James','Barry','UK');

-- unique records
INSERT INTO emp(FirstName,LastName,Country )values ('Sonu','Shaikh','IND');
INSERT INTO emp(FirstName,LastName,Country )values ('Shama','Banoo','IND');

SELECT * FROM emp;

-- SELECT DUPLCATE ROWS
SELECT FIRSTNAME,LASTNAME,COUNTRY FROM EMP
GROUP BY (FIRSTNAME,LASTNAME,COUNTRY)
HAVING COUNT(*) > 1;


-- ROW ID

SELECT MIN(ROWID) FROM EMP GROUP BY (FIRSTNAME,LASTNAME,COUNTRY);

-- 
SELECT * FROM ALL_TABLES WHERE OWNER = 'SH';

SELECT * FROM SH.SALES;
SELECT * FROM SH.PRODUCTS;

SELECT PROD_ID,COUNT(PROD_ID) AS COUNTS FROM SH.SALES GROUP BY PROD_ID ORDER BY 2 DESC;

SELECT * FROM SH.SALES;

-- TOTAL SALE BY PRODUCT
SELECT PROD_ID, SUM(AMOUNT_SOLD)AS TOTAL_SALES FROM SH.SALES GROUP BY PROD_ID;

-- DUPLICATE RECORDS
SELECT CUST_ID,PROD_ID,COUNT(PROD_ID) AS NO_OF_PIECES FROM SH.SALES GROUP BY (cust_id,prod_id) HAVING COUNT(prod_id) > 1 ORDER BY PROD_ID DESC;

-- NUMBER OF ORDER ON PERTICULAR DAY
SELECT TIME_ID, COUNT(TIME_ID) FROM SH.SALES GROUP BY (TIME_ID) ORDER BY 2 DESC;

-- TOTAL DISTINCT DATES
SELECT COUNT(DISTINCT(TIME_ID)) AS TOTAL_DATES FROM SH.SALES;










